import { useEffect } from "react";
import type { StoreProduct } from "@/services/products";

export const siteUrl = (import.meta.env.VITE_SITE_URL || "https://qyvero.com").replace(/\/$/, "");
export const siteName = "QYVERO";
export const defaultDescription = "QYVERO is a luxury men's lifestyle brand for modern essentials, refined accessories, and everyday distinction.";
export const absoluteUrl = (path = "/") => `${siteUrl}${path.startsWith("/") ? path : `/${path}`}`;
export type SeoInput = { title: string; description: string; path: string; image?: string; keywords?: string; robots?: string; structuredData?: Record<string, unknown> | Array<Record<string, unknown>> };

export function seoHead(input: SeoInput) { const url = absoluteUrl(input.path); const image = input.image || absoluteUrl("/favicon.ico"); const title = input.title.includes(siteName) ? input.title : `${input.title} | ${siteName}`; return { meta: [{ title }, { name: "description", content: input.description }, { name: "keywords", content: input.keywords || "luxury men's lifestyle, accessories, QYVERO" }, { name: "author", content: siteName }, { name: "robots", content: input.robots || "index,follow" }, { property: "og:type", content: "website" }, { property: "og:site_name", content: siteName }, { property: "og:title", content: title }, { property: "og:description", content: input.description }, { property: "og:url", content: url }, { property: "og:image", content: image }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: title }, { name: "twitter:description", content: input.description }, { name: "twitter:image", content: image }], links: [{ rel: "canonical", href: url }] }; }

function setMeta(selector: string, attribute: "name" | "property", key: string, content: string) { let element = document.head.querySelector<HTMLMetaElement>(selector); if (!element) { element = document.createElement("meta"); element.setAttribute(attribute, key); document.head.appendChild(element); } element.content = content; }
export function Seo({ input }: { input: SeoInput }) { useEffect(() => { const head = seoHead(input); document.title = head.meta[0].title ?? document.title; for (const item of head.meta.slice(1)) { if ("name" in item) setMeta(`meta[name="${item.name}"]`, "name", item.name!, item.content!); else if ("property" in item) setMeta(`meta[property="${item.property}"]`, "property", item.property!, item.content!); } let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = absoluteUrl(input.path); const id = "qyvero-structured-data"; document.getElementById(id)?.remove(); if (input.structuredData) { const script = document.createElement("script"); script.id = id; script.type = "application/ld+json"; script.text = JSON.stringify(input.structuredData); document.head.appendChild(script); } return () => document.getElementById(id)?.remove(); }, [input]); return null; }

export const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: siteName, url: siteUrl, logo: absoluteUrl("/favicon.ico"), sameAs: ["https://www.instagram.com/qyvero", "https://www.facebook.com/qyvero", "https://www.tiktok.com/@qyvero"] };
export const websiteSchema = { "@context": "https://schema.org", "@type": "WebSite", name: siteName, url: siteUrl, potentialAction: { "@type": "SearchAction", target: `${absoluteUrl("/products")}?q={search_term_string}`, "query-input": "required name=search_term_string" } };
export function breadcrumbSchema(items: Array<{ name: string; path: string }>) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: absoluteUrl(item.path) })) }; }
export function productSchema(product: StoreProduct) { const image = product.images.map((item) => item.image_url); return { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.meta_description || product.description || product.short_description || defaultDescription, image: image.length ? image : [absoluteUrl("/apple-touch-icon.png")], sku: product.sku, brand: { "@type": "Brand", name: product.brand || siteName }, offers: { "@type": "Offer", priceCurrency: "EGP", price: Number(product.price), availability: product.stock > 0 ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", url: absoluteUrl(`/products/${product.slug}`) }, ...(product.reviews_count > 0 ? { aggregateRating: { "@type": "AggregateRating", ratingValue: Number(product.rating), reviewCount: product.reviews_count, bestRating: 5, worstRating: 1 } } : {}) }; }
