import { Link } from "@tanstack/react-router";
import { Minus, PackageOpen, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { useCart } from "@/hooks/use-cart";
import { useLocale } from "@/providers/LocaleProvider";

const money = (value: number) => `${value.toLocaleString()} EGP`;

export function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const { t } = useLocale();
  if (!items.length) return <main className="min-h-screen bg-noise px-4 pb-32 pt-12 sm:px-6"><div className="mx-auto max-w-5xl"><EmptyState icon={<PackageOpen className="size-6" />} title={t("cart.emptyTitle")} description={t("cart.emptyDescription")} action={<Button asChild variant="outline"><Link to="/products">{t("cart.continueShopping")}</Link></Button>} /></div></main>;
  return <main className="min-h-screen bg-noise px-4 pb-24 pt-12 sm:px-6 sm:pb-32 sm:pt-20"><section className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-[11px] font-semibold uppercase tracking-[0.35em] text-teal">{t("cart.eyebrow")}</p><h1 className="text-display mt-3 text-3xl font-light sm:text-4xl">{t("cart.title")}</h1></div><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{items.map((item) => <article key={item.key} className="grid grid-cols-[5rem_minmax(0,1fr)] gap-4 rounded-3xl border border-white/10 bg-white/[0.02] p-4 sm:flex sm:p-5"><div className="size-20 shrink-0 overflow-hidden rounded-2xl bg-neutral-950">{item.image_url && <img src={item.image_url} alt={item.name} className="size-full object-cover" />}</div><div className="min-w-0"><div className="flex items-start justify-between gap-3"><Link to="/products/$productId" params={{ productId: item.slug }} className="min-w-0 truncate text-sm font-medium hover:text-teal">{item.name}</Link><p className="shrink-0 text-sm font-medium sm:hidden">{money(item.price * item.quantity)}</p></div>{item.variantLabel && <p className="mt-1 text-xs text-muted-foreground">{item.variantLabel}</p>}<p className="mt-2 text-sm text-teal">{money(item.price)}</p><div className="mt-3 flex items-center gap-2"><Button type="button" variant="outline" size="icon" aria-label={t("product.decreaseQuantity")} onClick={() => updateQuantity(item.key, item.quantity - 1)}><Minus /></Button><span className="min-w-7 text-center text-sm">{item.quantity}</span><Button type="button" variant="outline" size="icon" aria-label={t("product.increaseQuantity")} disabled={item.quantity >= item.stock} onClick={() => updateQuantity(item.key, item.quantity + 1)}><Plus /></Button><Button type="button" variant="ghost" size="icon" className="text-red-300" aria-label={t("cart.removeItem")} onClick={() => removeItem(item.key)}><Trash2 /></Button></div></div><p className="hidden text-sm font-medium sm:block">{money(item.price * item.quantity)}</p></article>)}</div><aside className="h-fit rounded-3xl border border-white/10 bg-white/[0.02] p-5 sm:p-6"><div className="flex items-center gap-2"><ShoppingBag className="size-4 text-teal" /><h2 className="font-medium">{t("cart.summary")}</h2></div><div className="mt-6 flex justify-between border-t border-white/10 pt-5 text-sm"><span className="text-muted-foreground">{t("checkout.subtotal")}</span><span>{money(subtotal)}</span></div><Button asChild className="mt-6 w-full rounded-full"><Link to="/checkout">{t("cart.checkout")}</Link></Button><Button asChild variant="outline" className="mt-3 w-full rounded-full"><Link to="/products">{t("cart.continueShopping")}</Link></Button></aside></div></section></main>;
}
