import { supabase } from "@/lib/supabase";

export type DiscountType = "percentage" | "fixed";
export type Coupon = { id: string; code: string; description: string | null; discount_type: DiscountType; discount_value: number; minimum_order: number; maximum_discount: number | null; usage_limit: number | null; usage_count: number; used_count: number; first_order_only: boolean; starts_at: string | null; expires_at: string | null; is_active: boolean; created_at: string };
export type CouponInput = Omit<Coupon, "id" | "usage_count" | "used_count" | "created_at" | "first_order_only"> & { first_order_only?: boolean };
export type CouponValidation = { valid: boolean; discountAmount: number; finalTotal: number; reason: string | null };
const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message); };
const normalize = (coupon: Coupon): Coupon => ({ ...coupon, code: coupon.code.toUpperCase(), discount_value: Number(coupon.discount_value), minimum_order: Number(coupon.minimum_order), maximum_discount: coupon.maximum_discount == null ? null : Number(coupon.maximum_discount), usage_count: Number(coupon.usage_count), used_count: Number(coupon.usage_count) });

export async function getCoupons(): Promise<Coupon[]> { const { data, error } = await supabase.from("coupons").select("*").order("created_at", { ascending: false }); fail(error); return (data ?? []).map((coupon) => normalize(coupon as Coupon)); }
export async function createCoupon(input: CouponInput): Promise<Coupon> { const { data, error } = await supabase.from("coupons").insert({ ...input, code: input.code.trim().toUpperCase(), description: input.description?.trim() || null }).select().single(); fail(error); return normalize(data as Coupon); }
export async function updateCoupon(id: string, input: Partial<CouponInput>): Promise<Coupon> { const { data, error } = await supabase.from("coupons").update({ ...input, ...(input.code ? { code: input.code.trim().toUpperCase() } : {}), ...(input.description !== undefined ? { description: input.description?.trim() || null } : {}) }).eq("id", id).select().single(); fail(error); return normalize(data as Coupon); }
export async function deleteCoupon(id: string) { const { error } = await supabase.from("coupons").delete().eq("id", id); fail(error); }
export async function validateCoupon(code: string, subtotal: number): Promise<CouponValidation> { const { data, error } = await supabase.rpc("validate_coupon", { p_code: code, p_subtotal: subtotal }); fail(error); const result = data?.[0]; if (!result) throw new Error("Unable to validate coupon."); return { valid: Boolean(result.valid), discountAmount: Number(result.discount_amount), finalTotal: Number(result.final_total), reason: result.reason ?? null }; }
export async function redeemCouponForOrder(orderId: string, code: string, subtotal: number, shipping: number) { const { data, error } = await supabase.rpc("redeem_coupon_for_order", { p_order_id: orderId, p_code: code, p_subtotal: subtotal, p_shipping: shipping }); fail(error); const result = data?.[0]; if (!result) throw new Error("Unable to apply coupon."); return { discountAmount: Number(result.discount_amount), finalTotal: Number(result.final_total) }; }
