import { Link, useNavigate } from "@tanstack/react-router";
import { AlertCircle, ChevronDown, ClipboardList, Package, ReceiptText, RotateCcw, ShoppingBag, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { StatusBadge } from "@/components/admin/AdminTable";
import { Button } from "@/components/ui/button";
import { useMyOrder, useMyOrders } from "@/hooks/use-orders";
import { useAuth } from "@/providers/AuthProvider";

const money = (value: number) => `${value.toLocaleString()} EGP`;
const label = (value: string | null) => (value ?? "Not specified").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const orderTone = (status: string) => ({ pending: "warning", confirmed: "info", preparing: "info", shipped: "info", delivered: "success", cancelled: "danger", returned: "danger", failed_delivery: "danger" }[status] ?? "neutral") as "warning" | "info" | "success" | "danger" | "neutral";
const paymentTone = (status: string) => ({ unpaid: "warning", waiting_review: "info", deposit_paid: "info", paid: "success", refunded: "neutral", rejected: "danger" }[status] ?? "neutral") as "warning" | "info" | "success" | "danger" | "neutral";

function OrderTimeline({ status }: { status: string }) {
  const steps = ["pending", "confirmed", "preparing", "shipped", "delivered"];
  const terminal = ["cancelled", "returned", "failed_delivery"].includes(status);
  const current = steps.indexOf(status);
  return <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="text-sm font-medium">Order timeline</h3>{terminal ? <div className="mt-3"><StatusBadge tone="danger">{label(status)}</StatusBadge></div> : <ol className="mt-4 grid gap-3 sm:grid-cols-5">{steps.map((step, index) => <li key={step} className={index <= current ? "text-teal" : "text-muted-foreground"}><div className={`mb-2 h-1 rounded-full ${index <= current ? "bg-teal" : "bg-white/10"}`} /><p className="text-xs font-medium">{label(step)}</p></li>)}</ol>}</section>;
}

function OrderDetails({ orderId }: { orderId: string }) {
  const { data: order, isLoading, isError, refetch } = useMyOrder(orderId);
  if (isLoading) return <div className="mt-5 grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-2"><div className="h-32 animate-pulse rounded-2xl bg-white/[0.05]" /><div className="h-32 animate-pulse rounded-2xl bg-white/[0.05]" /></div>;
  if (isError || !order) return <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-5 text-sm text-muted-foreground">Unable to load order details.<Button variant="outline" size="sm" onClick={() => void refetch()}><RotateCcw />Retry</Button></div>;

  const address = order.shipping_address ?? { governorate: order.governorate ?? undefined, city: order.city ?? undefined, street: order.address ?? undefined };
  const proof = order.payments.flatMap((payment) => payment.proofs ?? [])[0];
  const addressFields = [["Country", address.country], ["Governorate", address.governorate], ["City", address.city], ["Street", address.street], ["Building", address.building], ["Floor", address.floor], ["Apartment", address.apartment], ["Notes", address.notes], ["Estimated delivery", address.estimated_delivery_days ? `${address.estimated_delivery_days} business day${address.estimated_delivery_days === 1 ? "" : "s"}` : null], ["Coupon", order.coupon_code ? `${order.coupon_code} (-${money(order.discount_amount)})` : null]].filter(([, value]) => Boolean(value));

  return <div className="mt-5 space-y-5 border-t border-white/10 pt-5"><OrderTimeline status={order.status} /><div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]">
    <section><h3 className="text-sm font-medium">Products</h3><div className="mt-3 space-y-3">{order.items.map((item) => { const image = item.product?.images?.slice().sort((a, b) => Number(b.is_primary) - Number(a.is_primary) || a.sort_order - b.sort_order)[0]; return <div key={item.id} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-3"><div className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-xl bg-white/[0.04] text-xs text-muted-foreground">{image ? <img src={image.image_url} alt={item.product_name} className="size-full object-cover" /> : <Package className="size-5" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.product_name}</p><p className="mt-1 text-xs text-muted-foreground">{item.quantity} × {money(item.unit_price)}</p></div><p className="shrink-0 text-sm font-medium">{money(item.total_price)}</p></div>; })}</div></section>
    <div className="space-y-5"><section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="text-sm font-medium">Shipping Information</h3><dl className="mt-3 grid gap-2 text-sm">{addressFields.length ? addressFields.map(([name, value]) => <div key={name} className="flex justify-between gap-4"><dt className="text-muted-foreground">{name}</dt><dd className="text-right">{value}</dd></div>) : <p className="text-muted-foreground">Shipping address unavailable.</p>}</dl></section><section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="text-sm font-medium">Payment Information</h3><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-4"><span className="text-muted-foreground">Method</span><span>{label(order.payment_method)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Status</span><StatusBadge tone={paymentTone(order.payment_status)}>{label(order.payment_status)}</StatusBadge></div>{proof && <a href={proof.image_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 pt-2 text-xs font-medium text-teal hover:text-teal/80"><ReceiptText className="size-4" />View Receipt</a>}</div></section><section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>{money(order.subtotal)}</span></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Shipping</span><span>{money(order.shipping_cost)}</span></div><div className="mt-3 flex justify-between border-t border-white/10 pt-3 font-semibold"><span>Grand Total</span><span>{money(order.total_amount)}</span></div></section></div>
  </div></div>;
}

export function MyOrdersPage() {
  const { user, loading } = useAuth();
  const navigate = useNavigate();
  const [openOrderId, setOpenOrderId] = useState<string | null>(null);
  const { data: orders = [], isLoading, isError, refetch } = useMyOrders();
  useEffect(() => { if (!loading && !user) navigate({ to: "/auth/signin", replace: true }); }, [loading, user, navigate]);
  if (loading || !user) return <main className="grid min-h-screen place-items-center bg-noise"><div className="size-8 animate-spin rounded-full border-2 border-teal border-t-transparent" /></main>;

  return <main className="min-h-screen bg-noise pb-24 pt-12 sm:pb-32"><section className="mx-auto max-w-5xl px-6 pt-16"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-1.5 text-[10px] font-medium uppercase tracking-[0.35em] text-foreground/85"><Truck className="size-3 text-teal" />Member Space</span><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-display text-4xl font-light leading-none sm:text-5xl">My <span className="italic text-teal">Orders.</span></h1><p className="mt-3 text-sm text-muted-foreground">Review your QYVERO purchases and delivery details.</p></div><Button variant="outline" asChild><Link to="/profile">Personal Information</Link></Button></div>
    <div className="mt-10 space-y-4">{isLoading ? Array.from({ length: 3 }, (_, index) => <div key={index} className="h-44 animate-pulse rounded-[2rem] border border-white/10 bg-white/[0.025]" />) : isError ? <div className="rounded-[2rem] border border-white/10 bg-white/[0.025] p-8 text-center"><AlertCircle className="mx-auto size-8 text-teal" /><h2 className="text-display mt-4 text-xl">We couldn't load your orders.</h2><p className="mt-2 text-sm text-muted-foreground">Please check your connection and try again.</p><Button className="mt-5" onClick={() => void refetch()}><RotateCcw />Try Again</Button></div> : orders.length === 0 ? <div className="rounded-[2rem] border border-white/10 bg-white/[0.025] p-10 text-center sm:p-14"><div className="mx-auto grid size-16 place-items-center rounded-2xl border border-teal/20 bg-teal/10 text-teal"><ShoppingBag className="size-7" /></div><h2 className="text-display mt-6 text-2xl">No orders yet</h2><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">Your QYVERO orders will appear here once you place them.</p><Button className="mt-6" asChild><Link to="/products">Start Shopping</Link></Button></div> : orders.map((order) => { const open = order.id === openOrderId; return <article key={order.id} className="rounded-[2rem] border border-white/10 bg-white/[0.025] p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[1.2fr_repeat(4,minmax(0,1fr))_auto] lg:items-center"><div><p className="text-[10px] uppercase tracking-[0.24em] text-muted-foreground">Order Number</p><p className="mt-1 font-medium">{order.order_number}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(order.created_at).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Order Status</p><div className="mt-2"><StatusBadge tone={orderTone(order.status)}>{label(order.status)}</StatusBadge></div></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Payment</p><div className="mt-2"><StatusBadge tone={paymentTone(order.payment_status)}>{label(order.payment_status)}</StatusBadge></div><p className="mt-1 text-xs text-muted-foreground">{label(order.payment_method)}</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Items</p><p className="mt-2 text-sm">{order.items_count} item{order.items_count === 1 ? "" : "s"}</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Grand Total</p><p className="mt-2 text-sm font-semibold">{money(order.total_amount)}</p></div><Button variant="outline" className="w-full lg:w-auto" onClick={() => setOpenOrderId(open ? null : order.id)}>View Details<ChevronDown className={`transition-transform ${open ? "rotate-180" : ""}`} /></Button></div>{open && <OrderDetails orderId={order.id} />}</article>; })}</div>
  </section></main>;
}
