create table public.newsletter_subscribers (id uuid primary key default gen_random_uuid(), email text not null unique, subscribed_at timestamptz not null default now(), is_active boolean not null default true);
create table public.email_settings (id boolean primary key default true check (id = true), sender_name text not null default 'QYVERO', sender_email text, reply_to text, updated_at timestamptz not null default now());
insert into public.email_settings (id) values (true) on conflict do nothing;
create table public.email_queue (id uuid primary key default gen_random_uuid(), event_type text not null check (event_type in ('order_confirmation','order_status','payment_confirmed','payment_rejected','review_request','test')), order_id uuid references public.orders(id) on delete cascade, recipient text not null, payload jsonb not null default '{}'::jsonb, status text not null default 'pending' check (status in ('pending','processing','sent','failed')), attempts integer not null default 0, scheduled_at timestamptz not null default now(), processing_at timestamptz, sent_at timestamptz, last_error text, created_at timestamptz not null default now());
create index email_queue_pending_idx on public.email_queue (scheduled_at) where status = 'pending';

create or replace function public.enqueue_order_email() returns trigger language plpgsql security definer set search_path = '' as $$ begin if new.customer_email is not null then insert into public.email_queue(event_type,order_id,recipient) values ('order_confirmation',new.id,new.customer_email); end if; return new; end; $$;
create or replace function public.enqueue_order_status_email() returns trigger language plpgsql security definer set search_path = '' as $$ begin if new.status is distinct from old.status and new.customer_email is not null then insert into public.email_queue(event_type,order_id,recipient,payload,scheduled_at) values ('order_status',new.id,new.customer_email,jsonb_build_object('status',new.status),now()); if new.status = 'delivered' then insert into public.email_queue(event_type,order_id,recipient,scheduled_at) values ('review_request',new.id,new.customer_email,now() + interval '7 days'); end if; end if; return new; end; $$;
create or replace function public.enqueue_payment_email() returns trigger language plpgsql security definer set search_path = '' as $$ declare recipient_email text; begin if new.status is distinct from old.status and new.status in ('paid','rejected') then select customer_email into recipient_email from public.orders where id = new.order_id; if recipient_email is not null then insert into public.email_queue(event_type,order_id,recipient,payload) values (case when new.status = 'paid' then 'payment_confirmed' else 'payment_rejected' end,new.order_id,recipient_email,jsonb_build_object('reason',new.rejection_reason)); end if; end if; return new; end; $$;
drop trigger if exists queue_order_confirmation_email on public.orders; create trigger queue_order_confirmation_email after insert on public.orders for each row execute function public.enqueue_order_email();
drop trigger if exists queue_order_status_email on public.orders; create trigger queue_order_status_email after update of status on public.orders for each row execute function public.enqueue_order_status_email();
drop trigger if exists queue_payment_status_email on public.payments; create trigger queue_payment_status_email after update of status on public.payments for each row execute function public.enqueue_payment_email();

alter table public.newsletter_subscribers enable row level security; alter table public.email_settings enable row level security; alter table public.email_queue enable row level security;
create policy "Admins manage newsletter subscribers" on public.newsletter_subscribers for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins manage email settings" on public.email_settings for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins read email queue" on public.email_queue for select to authenticated using ((select public.is_admin()));

create or replace function public.subscribe_newsletter(p_email text) returns void language plpgsql security definer set search_path = '' as $$ begin insert into public.newsletter_subscribers(email) values (lower(trim(p_email))) on conflict (email) do update set is_active = true, subscribed_at = now(); end; $$;
create or replace function public.queue_test_email(p_recipient text) returns void language plpgsql security definer set search_path = '' as $$ begin if not public.is_admin() then raise exception 'Admin access required'; end if; insert into public.email_queue(event_type,recipient,payload) values ('test',lower(trim(p_recipient)),'{}'); end; $$;
create or replace function public.claim_email_queue(p_limit integer default 25) returns setof public.email_queue language plpgsql security definer set search_path = '' as $$ begin if auth.role() <> 'service_role' then raise exception 'Service role required'; end if; return query with claimed as (select id from public.email_queue where (status = 'pending' and scheduled_at <= now()) or (status = 'processing' and processing_at < now() - interval '10 minutes') order by scheduled_at for update skip locked limit greatest(1, least(p_limit,100))) update public.email_queue q set status='processing', attempts=q.attempts+1, processing_at=now() from claimed where q.id=claimed.id returning q.*; end; $$;
grant execute on function public.subscribe_newsletter(text) to anon, authenticated; grant execute on function public.queue_test_email(text) to authenticated;
